[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
loop_vault = "JQgKVw8JxAfEdNjpNgDuNCJCenF3cKxQHL7Hg7TwLnk"
loop_cred = "3FVxLJNThK8aqtRb65atTmkfJ2E1a2x5PfeSDEBzhetd"
loop_oxo = "5MPdaWr8CJCUvWigHSRy5xkvoTBKa1KfJHYRdKdMZ4t7"
loop_vtp = "3mP7L31af6MV6FnqWG6E78JELNuizWDwBK3rC3g3WjSK"
loop_avp = "FE3ZJBqVcqP6ar2pnndMghgNb3pi4mrjhVoAS7x4BVCA"
loop_shopping = "FSqRkH7nkGHP3VpHwFE667PVAfLKfSGaPMgTrXpJZJoJ"

[programs.devnet]
loop_vault = "JQgKVw8JxAfEdNjpNgDuNCJCenF3cKxQHL7Hg7TwLnk"
loop_cred = "3FVxLJNThK8aqtRb65atTmkfJ2E1a2x5PfeSDEBzhetd"
loop_oxo = "5MPdaWr8CJCUvWigHSRy5xkvoTBKa1KfJHYRdKdMZ4t7"
loop_vtp = "3mP7L31af6MV6FnqWG6E78JELNuizWDwBK3rC3g3WjSK"
loop_avp = "FE3ZJBqVcqP6ar2pnndMghgNb3pi4mrjhVoAS7x4BVCA"
loop_shopping = "FSqRkH7nkGHP3VpHwFE667PVAfLKfSGaPMgTrXpJZJoJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
