[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
loop_vault = "76FgGQNTw9maaV82og6U33KMZw4FCw9yGJu4M75hJ3Z7"
loop_cred = "FHVp7WrnUZq69aNZgYw2YNmitSdj8UCwoJ8C2A1M98JA"
loop_oxo = "3qxTuF17rTdGFECPimRWu51uUycSwAL4ebd7w9s2xx4z"
loop_vtp = "4D2PnJ4txLTQAqcoURt5eUQHMM85QsGPdGBHdsineuWj"
loop_avp = "H5c9xfPYcx6EtC8hpThshARtUR7tq1NfMJVrTx8z9Jcx"
loop_shopping = "D9EVmPZXMwqL3v9ebdpanyrJi3i1ZdfNRJo2MsZkd7qJ"

[programs.devnet]
loop_vault = "76FgGQNTw9maaV82og6U33KMZw4FCw9yGJu4M75hJ3Z7"
loop_cred = "FHVp7WrnUZq69aNZgYw2YNmitSdj8UCwoJ8C2A1M98JA"
loop_oxo = "3qxTuF17rTdGFECPimRWu51uUycSwAL4ebd7w9s2xx4z"
loop_vtp = "4D2PnJ4txLTQAqcoURt5eUQHMM85QsGPdGBHdsineuWj"
loop_avp = "H5c9xfPYcx6EtC8hpThshARtUR7tq1NfMJVrTx8z9Jcx"
loop_shopping = "D9EVmPZXMwqL3v9ebdpanyrJi3i1ZdfNRJo2MsZkd7qJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
